name: Build and Deploy pkgdown Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("devtools", "pkgdown"))
          devtools::install_deps(dependencies = TRUE)

      - name: Build site
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Commit and push docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m 'Deploy pkgdown site' || echo "No changes to commit"
          git push
